version: '3'

services:

  webapp:
    build: ./ops-exercise
    container_name: webapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - local_net
    healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 15s
            timeout: 10s
            retries: 5

  db:
    build: ./ops-exercise/db
    container_name: db
    networks:
      - local_net

networks:
  local_net:

